name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u stevemuir6 -p VV/H@4JVCUX!8bw
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test

      -name: Generate deployment package
       run: zip -r deploy.zip . -x '*.git*'

      -name: Deploy to EB
       uses: einaregilsson/beanstalk-deploy@v18
       with:
        aws_access_key: nowhere
        aws_secret_key: powerball
        application_name: frontend
        environment_name: frontend-environment
        version-label: 12345
        